
GOALS = [
    "Drink 8 glasses of water",
    "Do a full-body stretch when you wake up",
    "Take a 15-minute walk outdoors",
    "Read a book for 30 minutes",
    "Listen to a positive podcast",
    "Cook something healthy today",
    "Write down 3 things you enjoyed today",
    "Go to bed before 11 PM",
    "Eat something fresh – fruit or veggie",
    "Turn off your phone 1 hour before sleep",
    "Organize your room for 10 minutes",
    "Follow a 10-minute workout video",
    "Stay off social media for one full hour",
    "Clean your phone and keyboard",
    "Take 3 deep breaths before every meal",
    "Enjoy a warm drink without scrolling your phone",
    "Write a short journal entry about today",
    "Look in the mirror and think something kind",
    "Get 10 minutes of fresh air today",
    "Put away 5 things that are out of place",
    "Listen to your favorite album from start to finish",
    "Plan your meals for tomorrow",
    "Don’t complain for the entire day",
    "Try a quick yoga video to unwind",
    "Send a quick thank-you message to someone",
    "Take a 30-minute break without screens or noise",
    "Make your bed right after getting up",
    "Take a cold or cool shower",
    "Watch the sunset or sunrise",
    "Say no to one thing that drains your energy",
]
