# Generated by Django 5.2.4 on 2025-07-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_category_habitgoal_category_targetgoal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitgoal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='targetgoal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
