# Generated by Django 5.2.4 on 2025-07-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_habitgoal_is_completed_targetgoal_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetgoal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
