# Generated by Django 5.2.4 on 2025-07-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_targetgoal_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitgoal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
