# Generated by Django 5.2.4 on 2025-07-31 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_simplegoal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleGoal',
        ),
    ]
