# Generated by Django 5.2.4 on 2025-08-01 16:58

from django.db import migrations


def create_default_categories(apps, schema_editor):

    CategoryModel = apps.get_model('goals', 'Category')


    SYSTEM_CATEGORY_NAMES = [
        'Sport',
        'Education',
        'Wellness',
        'Finance',
        'Relationships',
    ]

    for category_name in SYSTEM_CATEGORY_NAMES:

        CategoryModel.objects.get_or_create(
            name=category_name,
            defaults={
                'is_system': True,

            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_delete_simplegoal'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
