# Generated by Django 5.2.4 on 2026-09-15 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0011_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitgoal',
            name='target_per_period',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
