# Generated by Django 5.2.4 on 2025-07-14 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0002_habitgoal_created_at_targetgoal_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('target_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='goals.targetgoal')),
            ],
        ),
    ]
