# Generated by Django 5.2.4 on 2025-07-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
