# Generated by Django 5.2.4 on 2025-08-01 16:42
from django.db import migrations

def create_admin_groups(apps, schema_editor):

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')


    SUPER_ADMIN_GROUP_NAME = 'SuperAdmins'
    STAFF_ADMIN_GROUP_NAME = 'StaffAdmins'


    TARGET_MODEL_NAMES = [
        'habitgoal',
        'targetgoal',
        'habitcheck',
        'step',
        'category',
        'note',
    ]


    FULL_CRUD_OPERATIONS = ['add', 'change', 'delete', 'view']
    VIEW_CHANGE_OPERATIONS = ['change', 'view']


    super_admin_group, _ = Group.objects.get_or_create(name=SUPER_ADMIN_GROUP_NAME)
    staff_admin_group, _ = Group.objects.get_or_create(name=STAFF_ADMIN_GROUP_NAME)


    full_permission_codenames = [
        f"{operation}_{model_name}"
        for model_name in TARGET_MODEL_NAMES
        for operation in FULL_CRUD_OPERATIONS
    ]
    staff_permission_codenames = [
        f"{operation}_{model_name}"
        for model_name in TARGET_MODEL_NAMES
        for operation in VIEW_CHANGE_OPERATIONS
    ]


    full_permissions_queryset = Permission.objects.filter(codename__in=full_permission_codenames)
    staff_permissions_queryset = Permission.objects.filter(codename__in=staff_permission_codenames)


    super_admin_group.permissions.set(full_permissions_queryset)
    staff_admin_group.permissions.set(staff_permissions_queryset)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RunPython(create_admin_groups),
    ]
